#### 简单的例子

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

$$ 
\begin{bmatrix}
\overbrace{q_\text{The}}^\text{row vector} \\
q_\text{cow} \\
q_\text{jumped}
\end{bmatrix}
$$

#### 单词分开训练

In [2]:
# pytorch中的LSTM接受三维数据，如上图所示
#第一维是序列本身即如果是句子则是单词个数，
#第二维是mini-batch的个数，
#第三维是单个词向量的维度
lstm01 = nn.LSTM(3, 3)   # 输入三维数据，输出三维数据
inputs01 = [torch.randn(1,3) for _ in range(5)]    # 模拟五个单词的句子，单词词向量维度是3
inputs01

[tensor([[ 0.8584, -0.4522, -0.2769]]),
 tensor([[ 1.2667, -0.1537,  1.6023]]),
 tensor([[0.5256, 0.6136, 0.4005]]),
 tensor([[-0.7552, -0.5332, -1.1395]]),
 tensor([[0.0900, 0.5821, 0.0626]])]

In [18]:
# 初始化隐藏层即 a[0], h[0]   LSTM有两条线贯穿始终
hidden01 = (torch.randn(1,1,3), torch.randn(1, 1, 3))
hidden01

(tensor([[[-0.0343, -0.2791,  0.4836]]]),
 tensor([[[-1.1297,  1.4051,  1.8485]]]))

In [31]:
for i in inputs01:
    out01, hidden01 = lstm01(i.view(1, 1, -1), hidden01)
    print(out01)
    print()
    print(hidden01)
    print("---------------------------------")

tensor([[[ 0.2819,  0.2234, -0.1141]]], grad_fn=<StackBackward>)

(tensor([[[ 0.2819,  0.2234, -0.1141]]], grad_fn=<StackBackward>), tensor([[[ 0.4250,  0.7577, -0.1533]]], grad_fn=<StackBackward>))
---------------------------------
tensor([[[0.1028, 0.2091, 0.0778]]], grad_fn=<StackBackward>)

(tensor([[[0.1028, 0.2091, 0.0778]]], grad_fn=<StackBackward>), tensor([[[0.7733, 0.8781, 0.2533]]], grad_fn=<StackBackward>))
---------------------------------
tensor([[[ 0.3578,  0.3484, -0.1579]]], grad_fn=<StackBackward>)

(tensor([[[ 0.3578,  0.3484, -0.1579]]], grad_fn=<StackBackward>), tensor([[[ 0.5042,  0.5998, -0.1813]]], grad_fn=<StackBackward>))
---------------------------------
tensor([[[0.1813, 0.1406, 0.0445]]], grad_fn=<StackBackward>)

(tensor([[[0.1813, 0.1406, 0.0445]]], grad_fn=<StackBackward>), tensor([[[0.3372, 0.8399, 0.0912]]], grad_fn=<StackBackward>))
---------------------------------
tensor([[[0.1854, 0.4358, 0.0853]]], grad_fn=<StackBackward>)

(tensor([[[0.1854, 0.43

#### 单词合在一起训练

In [36]:
lstm02 = nn.LSTM(3, 3)   # 输入三维数据，输出三维数据
inputs02 = [torch.randn(1,3) for _ in range(5)]    # 模拟五个单词的句子，单词词向量维度是3
print(inputs02)
print("------------------------------------")
hidden02 = (torch.randn(1,1,3), torch.randn(1, 1, 3))
print(hidden02)
print("------------------------------------")
inputs02 = torch.cat(inputs02).view(len(inputs02), 1, -1)  # 修改序列长度维度为 5
hidden02 = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))
out02, hidden02 = lstm02(inputs02, hidden02)
print(out02)
print()
print(hidden02)

[tensor([[-1.2982, -0.0629, -0.3089]]), tensor([[ 1.7893,  0.4237, -0.3040]]), tensor([[ 0.0031, -1.5194, -0.3608]]), tensor([[-0.1000, -1.0359, -0.3672]]), tensor([[ 1.0311, -1.4525,  0.4833]])]
------------------------------------
(tensor([[[0.9352, 0.0712, 1.6371]]]), tensor([[[1.3713, 1.2862, 0.2090]]]))
------------------------------------
tensor([[[-0.2333,  0.2044,  0.2867]],

        [[-0.5073,  0.2041, -0.0039]],

        [[-0.2558,  0.1444, -0.0689]],

        [[-0.2057,  0.1001, -0.0840]],

        [[-0.2546,  0.1072, -0.1950]]], grad_fn=<StackBackward>)

(tensor([[[-0.2546,  0.1072, -0.1950]]], grad_fn=<StackBackward>), tensor([[[-0.4147,  0.1835, -0.2649]]], grad_fn=<StackBackward>))
